# Generated by Django 4.2.30 on 2026-06-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GadgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_picture', models.ImageField(upload_to='gadgets/')),
                ('cat_description', models.TextField()),
                ('category_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_typename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_dp', models.ImageField(upload_to='users/')),
                ('u_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_phone', models.CharField(max_length=15)),
                ('u_status', models.BooleanField(default=True)),
                ('u_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.country')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=100)),
                ('f_description', models.TextField()),
                ('f_on', models.DateTimeField(auto_now_add=True)),
                ('f_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_detail', models.TextField()),
                ('c_photo', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('c_on', models.DateTimeField(auto_now_add=True)),
                ('c_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.state'),
        ),
    ]
