# Generated by Django 4.2.30 on 2026-06-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_description', models.TextField()),
                ('brand_logo', models.ImageField(upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='NewFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='new_furniture/')),
                ('available_quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
            ],
        ),
        migrations.CreateModel(
            name='OldFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_furniture_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='old_furniture/')),
                ('available_quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RentFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_furniture_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='rent_furniture/')),
                ('available_quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaintdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='furniturecategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_typename',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='building_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='u_gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='u_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RentFurnitureOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_startdate', models.DateField()),
                ('rent_enddate', models.DateField()),
                ('rent_bookdatetime', models.DateTimeField(auto_now_add=True)),
                ('rent_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.rentfurniture')),
                ('rent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='rentfurniture',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.furniturecategory'),
        ),
        migrations.CreateModel(
            name='OldFurnitureBuying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('old_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.oldfurniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='oldfurniture',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.furniturecategory'),
        ),
        migrations.CreateModel(
            name='NewFurnitureBuying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.newfurniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='newfurniture',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.furniturecategory'),
        ),
    ]
